// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IPhGear: typeof import('~icons/ph/gear')['default']
    IPhGearFill: typeof import('~icons/ph/gear-fill')['default']
  }
}

export {}
